// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKs9Jam2d17leVwKXU752P_Zn02qqbqLM',
    appId: '1:473177345955:web:182008fe90caa64ffe1416',
    messagingSenderId: '473177345955',
    projectId: 'libro-espresso-dss',
    authDomain: 'libro-espresso-dss.firebaseapp.com',
    storageBucket: 'libro-espresso-dss.firebasestorage.app',
    measurementId: 'G-F3MC9KBNVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSBrLxx0ojvThZMvE45V8ORNnsBgDl5Xc',
    appId: '1:473177345955:android:661f28e6ed3a28e6fe1416',
    messagingSenderId: '473177345955',
    projectId: 'libro-espresso-dss',
    storageBucket: 'libro-espresso-dss.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZvJIaR6xibhOvZad44M5tnXgqyO0cxQo',
    appId: '1:473177345955:ios:b2ac1b17caf55abbfe1416',
    messagingSenderId: '473177345955',
    projectId: 'libro-espresso-dss',
    storageBucket: 'libro-espresso-dss.firebasestorage.app',
    iosBundleId: 'com.example.libroEspressoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKs9Jam2d17leVwKXU752P_Zn02qqbqLM',
    appId: '1:473177345955:web:6d2c87dd6f1ba91bfe1416',
    messagingSenderId: '473177345955',
    projectId: 'libro-espresso-dss',
    authDomain: 'libro-espresso-dss.firebaseapp.com',
    storageBucket: 'libro-espresso-dss.firebasestorage.app',
    measurementId: 'G-D0NW9E6VPJ',
  );
}
